## Mulitiple Linear Regression 2(udemy)

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [45]:
data = pd.read_csv('50_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [46]:
print(data.isnull().sum())

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64


In [47]:
X = data.iloc[:,:-1].values
y = data.iloc[:,4].values
X,y

(array([[165349.2, 136897.8, 471784.1, 'New York'],
        [162597.7, 151377.59, 443898.53, 'California'],
        [153441.51, 101145.55, 407934.54, 'Florida'],
        [144372.41, 118671.85, 383199.62, 'New York'],
        [142107.34, 91391.77, 366168.42, 'Florida'],
        [131876.9, 99814.71, 362861.36, 'New York'],
        [134615.46, 147198.87, 127716.82, 'California'],
        [130298.13, 145530.06, 323876.68, 'Florida'],
        [120542.52, 148718.95, 311613.29, 'New York'],
        [123334.88, 108679.17, 304981.62, 'California'],
        [101913.08, 110594.11, 229160.95, 'Florida'],
        [100671.96, 91790.61, 249744.55, 'California'],
        [93863.75, 127320.38, 249839.44, 'Florida'],
        [91992.39, 135495.07, 252664.93, 'California'],
        [119943.24, 156547.42, 256512.92, 'Florida'],
        [114523.61, 122616.84, 261776.23, 'New York'],
        [78013.11, 121597.55, 264346.06, 'California'],
        [94657.16, 145077.58, 282574.31, 'New York'],
        [91749.1

In [48]:
# Encoding categorical data
# Encoding the Independent variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,3] = labelencoder_X.fit_transform(X[:,3])
onehotencoder = OneHotEncoder(categorical_features=[3]) 
X = onehotencoder.fit_transform(X).toarray()
X

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [49]:
X.dtype

dtype('float64')

In [50]:
X = pd.DataFrame(X)
X.head()
X.round(0)

0    1    2         3         4         5
0   0.0  0.0  1.0  165349.0  136898.0  471784.0
1   1.0  0.0  0.0  162598.0  151378.0  443899.0
2   0.0  1.0  0.0  153442.0  101146.0  407935.0
3   0.0  0.0  1.0  144372.0  118672.0  383200.0
4   0.0  1.0  0.0  142107.0   91392.0  366168.0
5   0.0  0.0  1.0  131877.0   99815.0  362861.0
6   1.0  0.0  0.0  134615.0  147199.0  127717.0
7   0.0  1.0  0.0  130298.0  145530.0  323877.0
8   0.0  0.0  1.0  120543.0  148719.0  311613.0
9   1.0  0.0  0.0  123335.0  108679.0  304982.0
10  0.0  1.0  0.0  101913.0  110594.0  229161.0
11  1.0  0.0  0.0  100672.0   91791.0  249745.0
12  0.0  1.0  0.0   93864.0  127320.0  249839.0
13  1.0  0.0  0.0   91992.0  135495.0  252665.0
14  0.0  1.0  0.0  119943.0  156547.0  256513.0
15  0.0  0.0  1.0  114524.0  122617.0  261776.0
16  1.0  0.0  0.0   78013.0  121598.0  264346.0
17  0.0  0.0  1.0   94657.0  145078.0  282574.0
18  0.0  1.0  0.0   91749.0  114176.0  294920.0
19  0.0  0.0  1.0   86420.0  153514.0       0.0
20  1.0  0.0  0.0   76254.0  113867.0  298664.0
21  0.0  0.0  1.0   78389.0  153773.0  299737.0
22  0.0  1.0  0.0   73995.0  122783.0  303319.0
23  0.0  1.0  0.0   67533.0  105751.0  304769.0
24  0.0  0.0  1.0   77044.0   99281.0  140575.0
25  1.0  0.0  0.0   64665.0  139553.0  137963.0
26  0.0  1.0  0.0   75329.0  144136.0  134050.0
27  0.0  0.0  1.0   72108.0  127865.0  353184.0
28  0.0  1.0  0.0   66052.0  182646.0  118148.0
29  0.0  0.0  1.0   65605.0  153032.0  107138.0
30  0.0  1.0  0.0   61994.0  115641.0   91131.0
31  0.0  0.0  1.0   61136.0  152702.0   88218.0
32  1.0  0.0  0.0   63409.0  129220.0   46085.0
33  0.0  1.0  0.0   55494.0  103057.0  214635.0
34  1.0  0.0  0.0   46426.0  157694.0  210798.0
35  0.0  0.0  1.0   46014.0   85047.0  205518.0
36  0.0  1.0  0.0   28664.0  127056.0  201127.0
37  1.0  0.0  0.0   44070.0   51283.0  197029.0
38  0.0  0.0  1.0   20230.0   65948.0  185265.0
39  1.0  0.0  0.0   38559.0   82982.0  174999.0
40  1.0  0.0  0.0   28754.0  118546.0  172796.0
41  0.0  1.0  0.0   27893.0   84711.0  164471.0
42  1.0  0.0  0.0   23641.0   96190.0  148001.0
43  0.0  0.0  1.0   15506.0  127382.0   35534.0
44  1.0  0.0  0.0   22178.0  154806.0   28335.0
45  0.0  0.0  1.0    1000.0  124153.0    1904.0
46  0.0  1.0  0.0    1315.0  115816.0  297114.0
47  1.0  0.0  0.0       0.0  135427.0       0.0
48  0.0  0.0  1.0     542.0   51743.0       0.0
49  1.0  0.0  0.0       0.0  116984.0   45173.0

In [51]:
# Row count of dataframe
# X.shape[0] or
len(X)

50

In [52]:
# column count of dataframe
# len(X.columns) or
X.shape[1]            

6

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [54]:
len(X_train)

40

In [55]:
len(X_test)

10

In [56]:
# We don't do feature scaling for multiple linear regresssion because library will take care of it

In [57]:
# Fitting multiple linear regression to the training set

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [58]:
# Prediction of the test set result(Performance of our regression  model on test data set)

y_pred = regressor.predict(X_test)
y_pred

array([103015.20159796, 132582.27760816, 132447.73845174,  71976.09851258,
       178537.48221055, 116161.24230166,  67851.69209676,  98791.73374686,
       113969.43533013, 167921.06569551])

In [59]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [60]:
# Do u think it's actually the optimal model that we can make with the dataset that we have here ?
# When we build this model we actually used all the independent variables, but what if among this independent variables there
# are some highly statistically significant i.e., have great impact on the dependent variable and some of them are not
# statistically significant at all
# that means if we remove the non statistically significant variables from the model we'll still get some amazing predictions.

# So, here our goal is to actually find a team an optimal team of independent variables so each independent variable in the
# team has great impact(highly statistically significant) and definetly has an effect on the dependent variable.
# and this effect can be positive i.e,for an increase of 1 unit of the independent variable the dependent variable increase
# or it can be negative i.e,for a decrease of 1 unit of the independent variable the dependent variable decrease.

In [61]:
#the principle of backward elemination is that we'll remove each independent variable that is not statistically significant
# (i.e., p-value > signif level(0.05)) one by one.

# S1 : Select a significant level to stay in the model (eg SL = 0.05)
# S2 : Fit the model with all possible predictors
# S3 : Consider the predictor with the highest P-value.If P > SL, go to S4, otherwise go to FIN
# S4 : Remove the predictor
# S5 : Fit model with out variable

# So we're  building the optimal model using "backward elimination"

In [62]:
import statsmodels.formula.api as sm

# we just need to add a column of ones in our matrix of features or matrix of independent variables 
# And to understand why we need to do this go through mutiple linear equation(y = b0+b1x1+....+bnxn)
# we notice in this equation that there is constant(b0) which is not associated with independent variable like 'x'(i.e, x0) 
# but we can associate 'x0' to this constant 'b0'(its actually 'x0 = 1')
# And actually this statsmodels library that we r using doesn't take into account this 'b0' constant, so we'll somehow need to
# add it in our matrix of independent variables.
# In most libraries that we use to build a linear regression model its definetely included the fact that there is a constant(b0)
# in the multiple linear regression equation, but it's not actually the case for this stats model library which we'll use to
# compute p-values and evaluate statistically significance of our independent variable

# that's why we need do do something here and if something is to actually add this column of ones here in our matrix of features
# X = np.append(arr = X,values = np.ones((50,1)),axis = 1)

# to prevent a datatype error from happening we need to convert this array of 1's into integer(i.e,np.ones((50,1)).astype(int))
# X = np.append(arr = X,values = np.ones((50,1)).astype(int),axis = 1)

# if we run the above code it'll add the column of 1's at the end of matrix of features X,and we would like to have it at the 
# beginning so in place of "arr = X take  np.ones((50,1)).astype(int)" and in palce of "values take X"

X = np.append(arr = np.ones((50,1)).astype(int),values = X,axis = 1)
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.6534920e+05, 1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.6259770e+05, 1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.5344151e+05, 1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.4437241e+05, 1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.4210734e+05, 9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.3187690e+05, 9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.3461546e+05, 1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.3029813e+05, 1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 0

In [69]:
X_opt = X[:,[0,1,2,3,4,5,6]]
regressor_OLS = sm.OLS(endog = y,exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Tue, 07 Jan 2020   Prob (F-statistic):           1.34e-27
Time:                        19:40:46   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.763e+04   5073.636      7.417      0.000    2.74e+04    4.79e+04
x1          1.249e+04   2449.797      5.099      0.000    7554.868    1.74e+04
x2          1.269e+04   2726.700      4.654      0.000    7195.596    1.82e+04
x3          1.245e+04   2486.364      5.007      0.000    7439.285    1.75e+04
x4             0.8060      0.046     17.369      0.000       0.712       0.900
x5            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x6             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     2.69e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [70]:
#while removing the variable with highest p-values go by index of array X 
#(constant(b0) with dummy varble(x0) with 1's has index 0 )
X_opt = X[:,[0,1,2,3,4,6]]
regressor_OLS = sm.OLS(endog = y,exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     215.8
Date:                Tue, 07 Jan 2020   Prob (F-statistic):           9.72e-29
Time:                        19:41:20   Log-Likelihood:                -525.53
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1071.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.525e+04   2100.376     16.782      0.000     3.1e+04    3.95e+04
x1          1.171e+04   1910.312      6.130      0.000    7861.854    1.56e+04
x2          1.185e+04   2170.903      5.459      0.000    7477.785    1.62e+04
x3          1.169e+04   1988.428      5.879      0.000    7684.996    1.57e+04
x4             0.7967      0.042     18.771      0.000       0.711       0.882
x5             0.0298      0.016      1.842      0.072      -0.003       0.062
==============================================================================
Omnibus:                       14.640   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.037
Skew:                          -0.938   Prob(JB):                     2.70e-05
Kurtosis:                       5.565   Cond. No.                     6.69e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.33e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [72]:
X_opt = X[:,[0,1,2,3,4]]
regressor_OLS = sm.OLS(endog = y,exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     272.4
Date:                Tue, 07 Jan 2020   Prob (F-statistic):           2.76e-29
Time:                        19:56:14   Log-Likelihood:                -527.35
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      46   BIC:                             1070.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.686e+04   1959.786     18.806      0.000    3.29e+04    4.08e+04
x1          1.189e+04   1956.677      6.079      0.000    7955.697    1.58e+04
x2          1.306e+04   2122.665      6.152      0.000    8785.448    1.73e+04
x3           1.19e+04   2036.022      5.847      0.000    7805.580     1.6e+04
x4             0.8530      0.030     28.226      0.000       0.792       0.914
==============================================================================
Omnibus:                       13.418   Durbin-Watson:                   1.122
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.605
Skew:                          -0.907   Prob(JB):                     0.000150
Kurtosis:                       5.271   Cond. No.                     3.70e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.74e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [76]:
pd.DataFrame(X_opt).head()

0    1    2    3          4
0  1.0  0.0  0.0  1.0  165349.20
1  1.0  1.0  0.0  0.0  162597.70
2  1.0  0.0  1.0  0.0  153441.51
3  1.0  0.0  0.0  1.0  144372.41
4  1.0  0.0  1.0  0.0  142107.34

In [ ]:
# Since x0,x1,x2,x3 are dummy variables that we assigned in our data
# then the conclusion is that the optimal team(X_opt) of independent variables that can predict a dependent variable 
#with highest statistical significance(the strogest impact) is actually composed of only 1 independent variable viz"R&D spend" 